name: Graphs CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  graphs:
    runs-on: ubuntu-latest
    steps:
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: "graphs"
