name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run upptime
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
